### ISSUE TITLE
Add default environment variable values

### ISSUE THREAD

**Issue by stefan-pdx** [hadim/docker-omero#2]
Docker Compose now [supports](https://docs.docker.com/compose/compose-file/#variable-substitution) default values for environment variables in the form of `${MYVARIABLE-default_value}`. This would simplify the build process.

**Comment by hadim** [comment]
From what I know they only support variable substitution without default value : 

> Both $VARIABLE and ${VARIABLE} syntax are supported. Extended shell-style features, such as ${VARIABLE-default} and ${VARIABLE/foo/bar}, are **not** supported.

Did I miss something ?
What changes do you suggest in the `docker-omero` repo ?

**Comment by stefan-pdx** [comment]
Oh -- gah. Sorry about that. RTFM :facepalm:

Disregard!

**Comment by hadim** [comment]
:-)

I hope they will add this feature soon !
