### ISSUE TITLE
not connect via omero insight

### ISSUE THREAD

**Issue by cedunia** [hadim/docker-omero#4]
I get a successful connection with omero web but I can't with omero insight (login failure). I've put as server address **_localhost_** and port **_80_** and fill login **_root_** and password **_password_**
Can you help me ?

Thanks!

**Comment by hadim** [comment]
Could you try https://localhost ?

**Comment by cedunia** [comment]
connection in ssl mode or unsecure mode works very well with omero.web. I've always login failure in ssl or unsecure mode with insight. I've got the same version that omero web 5.2.1-ice35-b15. i try both http://localhost, https://localhost with port 80 without success.
![insight_bug](https://cloud.githubusercontent.com/assets/7711188/18662397/82c53146-7f1a-11e6-8631-4ff3cd82df3c.png)

**Comment by hadim** [comment]
The port `80` is for OMERO Web **only**. If you want to use the desktop client (Insight) please use the following port `4064`.

Please tell me if it works.

**Comment by cedunia** [comment]
not works with port 4064 too

**Comment by hadim** [comment]
On the desktop client you need to check the small lock image next to the `LAN` on your screenshot. Then it should work.

**Comment by hadim** [comment]
I have updated the README file, it should be more clear now.

And I have also updated the images to use Ubuntu 16.04 and OMERO 5.2.5. 

To get the new changes, update the git repo with `git pull`.

**Comment by cedunia** [comment]
Now, i work with the small lock. Thanks very much for your help
